create table statehistorical (
    id serial primary key,
	date			  int,
	state                    text,
	positive                 int,
	negative                 int,
	pending                  int,
	hospitalizedCurrently    int,
	hospitalizedCumulative   int,
	inIcuCurrently           int,
	inIcuCumulative          int,
	onVentilatorCurrently    int,
	onVentilatorCumulative   int,
	recovered                int,
	death					 int,
	hospitalized             int,
	totalTestResults         int,
	hospitalizedIncrease     int,
	deathIncrease            int,
	negativeIncrease         int,
	positiveIncrease         int,
	totalTestResultsIncrease int,
)
