create table StateHistorical (
    id serial primary key,
	date					 int,
	state                    text,
	positive                 int,
	pospitalizedIncrease     int,
	positiveIncrease         int,
	negativeIncrease         int,
	deathIncrease            int,
	totalTestResultsIncrease int,
	negative                 int,
	pending                  text,
	hospitalizedCurrently    int,
	hospitalizedCumulative   int,
	inIcuCurrently           int,
	inIcuCumulative          int,
	onVentilatorCurrently    int,
	onVentilatorCumulative   int,
	recovered                int,
	hospitalized             int,
	total                    int,
	totalTestResults         int,
);
